const data = {
  products: [
    {
      name: "Nike Air Jordan High",
      slug: "nike air jordan high",
      category: "shoes",
      image: "/images/Nike Air Jordan 1.jpg",
      price: 850,
      brand: "Nike",
      rating: 4.0,
      numReviews: 10,
      countInStock: 12,
      discount: 10,
      description: "Nike Air Jordan series",
    },
    {
      name: "Nike Air Jordan Low",
      slug: "nike air jordan low",
      category: "shoes",
      image: "/images/Nike Air Jordan 2.jpg",
      price: 750,
      brand: "Nike",
      rating: 4.5,
      numReviews: 15,
      countInStock: 10,
      discount: 10,
      description: "Nike Air Jordan Low series",
    },
    {
      name: "Adidas Matchcourt",
      slug: "adidas matchcourt",
      category: "shoes",
      image: "/images/Adidas Matchcourt 1.jpg",
      price: 275,
      brand: "Adidas",
      rating: 3.5,
      numReviews: 20,
      countInStock: 8,
      discount: 10,
      description: "Adidas Skateboarding Series",
    },
    {
      name: "Adidas Nizza",
      slug: "adidas nizza",
      category: "shoes",
      image: "/images/Adidas Nizza 1.jpg",
      price: 225,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      countInStock: 5,
      discount: 10,
      description: "Adidas Shoes casual Series",
    },
    {
      name: "Vans Oldschool",
      slug: "vans oldschool",
      category: "shoes",
      image: "/images/Vans Old School 1.jpg",
      price: 185,
      brand: "Vans",
      rating: 5.0,
      numReviews: 50,
      countInStock: 0,
      discount: 5,
      description: "Vans Shoes Series",
    },
    {
      name: "Vans Slip On",
      slug: "vans slip on",
      category: "shoes",
      image: "/images/Vans Slip on 1.jpeg",
      price: 175,
      brand: "Vans",
      rating: 5.0,
      numReviews: 50,
      countInStock: 30,
      discount: 5,
      description: "Vans Shoes Series",
    },
    {
      name: "Puma Suede",
      slug: "puma suede",
      category: "shoes",
      image: "/images/Puma Suede 1.jpeg",
      price: 215,
      brand: "Puma",
      rating: 4.5,
      numReviews: 30,
      countInStock: 10,
      discount: 25,
      description: "Puma Shoes Series",
    },
  ],
};

export default data;
